# Build stage
FROM node:21.1.0

# Set working directory
WORKDIR /app

# Copy package.json file
COPY package.json ./

# Download dependencies
RUN npm install --legacy-peer-deps

# Copy the source code
COPY . .

RUN npm run build

# Expose the port the app runs on
EXPOSE 8083

CMD ["sh", "-c", "npm run start:prod"]

